#! /bin/sh

# There is no Xinerama or xrandr support yet,
# because you can choose your monitors
# completely manual: you can setup the monitors
# like this in your autostart:

# hc remove_monitor 1
# hc move_monitor 0 1280x1024+0+0
# hc use "${TAG_NAMES[0]}"
# hc add_monitor 1280x1024+1280+0 "${TAG_NAMES[1]}"

herbstclient move_monitor 0 1280x1024+0+0
herbstclient add_monitor 1280x1024+1280+0

# This would be the code to setup two monitors with a
# resolution of 1280x1024. The format for the monitor
# geometry is:
# 
# WIDTHxHEIGHTxHORIZONTALOFFSETxVERTICALOFFSET.
# 
# This means that you can setup multiple monitors,
# even if you just have one large monitor (e.g. a
# strange 22inch screen with 1920x1600 pixels).
# 
# So it actually is a feature: setup monitors
# independet from real monitors, xrandr, xinerama,...
