#!/bin/sh

xrandr --auto --output DVI-I-1 --left-of DVI-I-2 --output DVI-I-2 --rotate left

setxkbmap dz kinesis
xsetroot -cursor_name left_ptr
xrdb -merge ~/.Xresources

# set the wallpaper
if [ -x /usr/bin/feh ] ; then
    feh --bg-fill ~/Bilder/.wallpaper/paraglider.jpg
fi

# activate compositing
if [ -x /usr/bin/compton ] ; then
    compton -cC -i 1.0 -e 0.6 -m 0.9 -f &
fi

# hide the mouse pointer when not needed
if [ -x /usr/bin/unclutter ] ; then
    unclutter &
fi

# start screensaver daemon
if [ -x /usr/bin/xscreensaver ] ; then
    xscreensaver -nosplash &
fi

# start a dropbox client if present
if [ -x /opt/bin/dropbox ] ; then
    dropbox &
fi

# if gnome is installed, then use its session settings
if [ -x /usr/bin/gnome-settings-daemon ] ; then
    gnome-settings-daemon &
fi

export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export HTTP_PROXY="http://do2-dansguardian.isas.de:3128"

exec dbus-launch herbstluftwm --locked
