#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    cmds="$cmds , $@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# use the some swap functions to give hc some tiling gimmics
swap=~/.config/herbstluftwm/swap

# keybindings
Mod=Mod4
hc keybind $Mod-a spawn xscreensaver-command -lock
hc keybind $Mod-Shift-q quit
hc keybind $Mod-colon reload
hc keybind $Mod-d spawn $swap auto
hc keybind $Mod-Shift-d spawn $swap close
hc keybind $Mod-Return spawn $swap stack_spawn xterm

# tags
TAG_NAMES=( {7,5,3,1,2,4,6,8} )
TAG_KEYS=( {7,5,3,1,2,4,6,8} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# move around tags
hc keybind $Mod-r     use_index +1 --skip-visible
hc keybind $Mod-g     use_index -1 --skip-visible
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible

# switch foctused monitor to previous tags
hc keybind $Mod-i use_previous

# move clients to different tags
hc keybind $Mod-p           move_index +1 --skip-visible
hc keybind $Mod-comma       move_index -1 --skip-visible
hc keybind $Mod-Shift-Right move_index +1 --skip-visible
hc keybind $Mod-Shift-Left  move_index -1 --skip-visible

# move around panes
hc keybind $Mod-h focus left
hc keybind $Mod-t focus down
hc keybind $Mod-c focus up
hc keybind $Mod-n focus right

# move clients to different panes
hc keybind $Mod-o       shift left
hc keybind $Mod-e       shift down
hc keybind $Mod-period  shift up
hc keybind $Mod-u       shift right

# change pane configuration: adding and removing
#   values are multiples of the golden fraction
hc keybind $Mod-w split vertical  0.7669549  # =1-(8/13)^3
hc keybind $Mod-v split horizontal 0.6213018 # =1-(8/13)^2
hc keybind $Mod-q remove

# change pane configuration: resize
RESIZESTEP=0.02
hc keybind $Mod-Shift-h resize left +$RESIZESTEP
hc keybind $Mod-Shift-t resize down +$RESIZESTEP
hc keybind $Mod-Shift-c resize up +$RESIZESTEP
hc keybind $Mod-Shift-n resize right +$RESIZESTEP

# change pane configuration: layout
hc keybind $Mod-s cycle_layout 1 max grid
hc keybind $Mod-l cycle_layout 1 horizontal vertical

# change pane configuration: tiling, floating and fullscreen
hc keybind $Mod-f pseudotile toggle
hc keybind $Mod-Shift-f floating toggle
hc keybind $Mod-m fullscreen toggle

# move around monitors
hc keybind $Mod-Shift-space cycle_monitor
hc keybind $Mod-Shift-g focus_monitor -1
hc keybind $Mod-Shift-r focus_monitor +1

# cycle through clients
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-space       cycle
#hc keybind $Mod-q jumpto urgent

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# colors
hc set frame_border_normal_color  '#000000'
hc set frame_border_active_color  '#FFFFFF'
hc set frame_bg_normal_color      '#222222'
hc set frame_bg_active_color      '#565656'
hc set window_border_normal_color '#454545'
hc set window_border_active_color '#9fbc00'

# transparity
hc set frame_bg_transparent 1
hc set frame_active_opacity 0
hc set frame_normal_opacity 0

# gaps
hc set frame_gap 2
hc set frame_padding 1
hc set frame_border_width 1
hc set always_show_frame 0
hc set window_gap -2
hc set window_border_width 1
hc set window_border_inner_width 1
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# menu
hc keybind $Mod-b spawn $swap master_spawn dmenu_run -nb "#535353" -nf "#EEEEEE" -sf "#EEEEEE" -sb "#53BBCB"

# sound
hc keybind $Mod-k spawn "amixer -- sset PCM playback 5%+"
hc keybind $Mod-j spawn "amixer -- sset PCM playback 5%-"
hc keybind $Mod-z spawn "amixer -- sset PCM toggle"

# rules

hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=off # normally do not focus new clients

# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# unlock, just to be sure
hc unlock

herbstclient chain $cmds&

# the panel
panel=~/.config/herbstluftwm/tint2.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
$panel

###  # find the panel
###  panel=~/.config/herbstluftwm/panel.sh
###  [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
###  for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
###      # start it on each monitor
###      $panel $monitor &
###  done
