#!/usr/bin/env python3

# OS Input / Output
import sys

from subprocess import Popen
from subprocess import PIPE
from subprocess import run

hc = 'herbstclient'

#-nb "#535353" -nf "#EEEEEE" -sf "#EEEEEE" -sb "#53BBCB"

def find_focused_tag():
    command = 'herbstclient tag_status'
    out = Popen([command], shell=True, stdout=PIPE)
    tag = [line.decode('utf-8') for line in out.stdout][0].split('\t')
    tag = tag[['#' in name for name in tag].index(True)][1:]
    out.terminate()
    return(tag)

default = ['email', 'web', 'project', 'mri', 'bio', 'neuro', 'genes', 'clinical', 'help', 'config']
default = '\n'.join(default)

def define_new_tag_name(default):
    out = Popen(['echo "' + default + '" | dmenu'], shell=True, stdout=PIPE)
    tag = [line.decode('utf-8').rstrip() for line in out.stdout][0]
    out.terminate()
    return(tag)

def rename_tag(oldtag, newtag):
    command = 'herbstclient rename'
    x = run([' '.join([command, oldtag, newtag])], shell=True, check=True)
    return(x)

#x = run(['ls', '-l'], shell=True, check=True)
#x = run([hc, 'rename', oldtag, newtag], shell=True, check=True)

if __name__ == '__main__':
    oldtag = find_focused_tag()
    newtag = define_new_tag_name(default)
    rename_tag(oldtag, newtag)
    print('Renamed tag from %s to %s' % (oldtag, newtag))
