#!/usr/bin/env python3

# OS Input / Output
import sys

from subprocess import Popen
from subprocess import PIPE
from subprocess import run

hc = 'herbstclient'

#-nb "#535353" -nf "#EEEEEE" -sf "#EEEEEE" -sb "#53BBCB"

def get_tags():
    command = 'herbstclient tag_status'
    tags = run([command], shell=True, stdout=PIPE, check=False)
    tags = tags.stdout.decode('utf-8').strip().split('\t')
    tags.remove(tags[['#' in name for name in tags].index(True)])
    tags = [x[1:] for x in tags]
    tags = '\n'.join(tags)
    return(tags)

def ask_for_tag(tags):
    x = run(['echo "' + tags + '" | dmenu'], shell=True, stdout=PIPE, check=False)
    x = x.stdout.decode('utf-8').strip()
    return(x)

def move_to_tag(tag):
    command = 'herbstclient use'
    run([' '.join([command, tag])], shell=True, check=False)

if __name__ == '__main__':
    tags = get_tags()
    tag = ask_for_tag(tags)
    move_to_tag(tag)
